### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bachirelkhoury** [richardbiely/Voxelmetric#38]
Is there any documentation or guide somewhere? in particular about initial setup, using custom configuration to new worlds and perhaps even loading and manipulating chunks.

Only thing I could find is Alexstv.com which is down.

Happy to contribute to the project as well, just need to know whether there are any docs that accelerate or avoid too much reverse engineering...

**Comment by richardbiely** [comment]
Unfortunatelly, there is no documentation for Voxe(lmetric) anywhere. This project is still in its' alpha state and constantly changing so all you can rely on are comments in the code. However, it should not be too difficult to understand how things work on a higher level.

In my opinion, Alexstv.com will not help you because the tutorial code is different and does not cover many areas which you can actually find in the repository at https://github.com/Voxelmetric/Voxelmetric1. And even if you found something helpful there, it would not help you much because Voxe(lmetric) has changed the original project vastly.

**Comment by XeonG** [comment]
Over the months I've come to have some vague understanding of its code structure... I'm still stumped as to adding block rotations.. not the bit stuff got that figured out .. just where to hook that stuff all in so its sets the texture based on it, I'll figure it out eventually 🗡

Anyway I hope you got some good features planned for it this year Richard (Happy new year btw)  my game is approaching some early alpha testing but the single block material limitation ie can't have no glass block/material (and also with 3d model block types also getting there texture packed into it, instead of being able to specify it using a separate material/shader is a bit annoying)  but its so core to the engine and I have no idea on that stuff, so I'm hoping you do something with it at some point.

Perhaps a question for another topic, but is there anyway to have chunk sizes not be cubed.. ie 32x32x4  or some other much smaller depth value, sort of for a 2.5d mode where the reduced chunk size could possibly squeeze some better performance out by not having each chunk be that large in the direction its not needed in anyway..

**Comment by Crayder** [comment]
>but is there anyway to have chunk sizes not be cubed.. ie 32x32x4 or some other much smaller depth value

Yes, this is possible. You just have to go change all of the appropriate `16`'s to the desired size. I changed the chunk size in mine to 16x16x128, which is the size used in Survivalcraft, which is what my project is designed for, editing Survivalcraft maps. My project is currently paused however...

**Comment by richardbiely** [comment]
No it is not possible. Voxe(lmetric) does not and mostly likely will not support asymmetrical chunks sizes for there's simply not enough reasons to do it. Overall it just adds to complexity.

Only very little performance wasted by having it that way. Chunk geometry is generated only where there's data so if you fill only 32x32x4 of your chunk then only this part is going to be processed (currently turned off, though, for various test purposes).
Once a proper in-memory compression is implemented (demo already in the code, just not turned on) it won't fall behind in terms of memory consumption either.
