### ISSUE TITLE
Missing namespaces

### ISSUE THREAD

**Issue by jaspercayne** [richardbiely/Voxelmetric#40]
I might be missing something here, but a clean import of the newest commit throws two missing namespaces in VoxeUnity/Editor/EditBlocks.cs at lines 8 and 9.

BlockController and BlockDefinition are both missing and I didn't see anything appropriate in the source files to change them to. I know you did a ton of work changing around how blocks get defined and I'm not sure how to get this engine running in its current state. If anyone knows how to tackle this, I would appreciate an assist.

EDIT: I suppose that I should clarify the fact that I know I can do away with the Editor folder entirely, but I was hoping to try and get that window working with the rewrite of the engine. If there is already something in the works for that and it isn't publicly available yet, then I just won't bother.

**Comment by richardbiely** [comment]
Well, I never touched those files and I did not even know they existed until now :)
I will take a look at them and see what can be done about that.

**Comment by richardbiely** [comment]
It turns out this code did not work in the original repository as well. It looks outdated/deprecated.

The original author might have tried to create some sort of an editor where you can define your own biomes, layers and block properties with it
I will leave it as it is for now because Voxe(lmetric) will try to have something similar in the future. From looking at it I will most likely drop the existing code but will at least use it as an inspiration.
