### ISSUE TITLE
Defining the Maximum Height of the World and Chunk Draw Distance

### ISSUE THREAD

**Issue by ghost** [richardbiely/Voxelmetric#44]
Another thing that's come up is that I'm looking for a way to define the maximum world height in chunks and the distance at which chunks are drawn.

The first is, I'd like to expand the size of hills into more realistic mountains, and I'm not sure where the max height is defined, and thus where to change it. In attempting to define realistic mountains I did, however, learn how to create large rolling sand dunes. It's pretty awesome. I'd like to upload a picture as soon as I can figure out configurations.

The second is that I'd like to increase the distance at which chunks are loaded/drawn and unloaded, and be able to define from what height chunks should also not be drawn (for example, from my previous "mountain" request). I wanna work on giving the world a much more open feel from the player's perspective while sacrificing the ability to dig and modify voxels.

**Comment by richardbiely** [comment]
The world is infinite by default. You can influence min/max Y axis, though. In order to do so you need to modify "maxY"/"minY" in your world's config.

It is currently rather performance demanding to render large distances (no LOD implemented). Therefore, I would recommend setting "Vertical Chunk Loading" to e. g. 4 or 5 and check the "Follow Camera" checkbox on the "Load Chunks Simple" MonoBehavior. Your world generator will no longer be fixed to [x,0,z] and will generate around the camera instead.
