### ISSUE TITLE
Run Voxelmetric on Android

### ISSUE THREAD

**Issue by ggascon** [richardbiely/Voxelmetric#59]
A few days ago I discovered this project and I am really impressed with its performance, really awesome! When I tried to run on Android to check if it behaves similar to PC Platform,  it shows default unity screen, no chunk is loaded and several "Unreachable code detected" warnings appear on the console. I've been inspecting the PlatformSpecificContent class code but I'm lost.

Could you tell me the steps I need to follow to run Voxelmetric on android? Thanks

**Comment by richardbiely** [comment]
There is nothing in particular that would block running Voxe(lmetric) on Android or any other platform supported by Unity3D. If it does not run I am sure there is an explanation for that. Maybe the Assets folder is not packed into the apk? I'd try placing the Assets folder to the same place as your apk. Maybe it will work (honestly, I have virtually no exprience with the platform so this is just a guess). 

You are safe to ignore those warning. They are only there because some code paths are dependent on global constants. For instance, enabling mutlithreaded I/O is a matter of setting a bool constant. If the value is false, the code path for multithreaded I/O is never taken even if the code for it exists. And thus the warnings.
